-- Xóa toàn bộ schema nếu cần
-- DROP USER course CASCADE;

BEGIN
FOR rec IN (SELECT 1 FROM dba_users WHERE username = 'course') LOOP
      EXECUTE IMMEDIATE 'DROP USER course CASCADE';
END LOOP;
END;


-- Tạo người dùng (schema) mới
CREATE USER course IDENTIFIED BY 123456;
GRANT CONNECT, RESOURCE TO course;


-- chuyển đến schema mới tạo
ALTER SESSION SET current_schema = course;


-- Thêm các quyền cần thiết cho người dùng
GRANT UNLIMITED TABLESPACE TO course;            -- Cấp quyền cho course để sử dụng không giới hạn dung lượng trên tất cả các tablespace.
ALTER USER course QUOTA UNLIMITED ON USERS;      -- Thiết lập hạn mức sử dụng không giới hạn trên tablespace USERS cho người dùng course.


CREATE TABLE tb_role (
                         id INT GENERATED BY DEFAULT AS IDENTITY,
                         name VARCHAR2(50) NOT NULL,
                         description VARCHAR2(255),
                         is_delete INT DEFAULT 0,

                         PRIMARY KEY(id)
);

CREATE TABLE tb_user (
                         id INT GENERATED BY DEFAULT AS IDENTITY,
                         username VARCHAR2(100),
                         email VARCHAR2(200) UNIQUE NOT NULL,
                         password VARCHAR2(200) NOT NULL,
                         avatar VARCHAR2(255),
                         is_delete INT DEFAULT 0,
                         role_id INT,

                         PRIMARY KEY(id)
);

CREATE TABLE tb_category (
                             id INT GENERATED BY DEFAULT AS IDENTITY,
                             name VARCHAR2(50) NOT NULL,
                             is_delete INT DEFAULT 0,

                             PRIMARY KEY(id)
);

CREATE TABLE tb_course (
                           id INT GENERATED BY DEFAULT AS IDENTITY,
                           title VARCHAR2(255) NOT NULL,
                           price FLOAT,
                           lecturer VARCHAR2(50),
                           image VARCHAR2(255),
                           description VARCHAR2(1000),
                           create_date DATE,
                           is_top_course  INT DEFAULT 0,
                           is_free INT DEFAULT 0,
                           category_id INT,
                           is_public INT DEFAULT 0,
                           is_delete INT DEFAULT 0,

                           PRIMARY KEY(id)
);

CREATE TABLE tb_lession (
                            id INT GENERATED BY DEFAULT AS IDENTITY ,
                            name VARCHAR2(150) NOT NULL,
                            video_url VARCHAR2(255) NOT NULL,
                            is_success INT DEFAULT 0,
                            course_id INT,
                            is_delete INT DEFAULT 0,

                            PRIMARY KEY(id)
);

CREATE TABLE tb_user_course (
                                user_id INT,
                                course_id INT,
                                date_buy DATE,
                                is_delete INT DEFAULT 0,

                                PRIMARY KEY (user_id, course_id)
);

CREATE TABLE tb_comment (
                            id INT GENERATED BY DEFAULT AS IDENTITY,
                            description VARCHAR2(500),
                            rate INT,
                            date_comment DATE,
                            person_id INT,
                            course_id INT,
                            is_delete INT DEFAULT 0,

                            PRIMARY KEY(id)
);


-- Liên kết bảng tb_user với tb_role
ALTER TABLE tb_user ADD CONSTRAINT FK_user_role FOREIGN KEY(role_id) REFERENCES tb_role(id);

-- Liên kết bảng tb_course với tb_category
ALTER TABLE tb_course ADD CONSTRAINT FK_course_category FOREIGN KEY(category_id) REFERENCES tb_category(id);

-- Liên kết bảng tb_lession với tb_course
ALTER TABLE tb_lession ADD CONSTRAINT FK_lession_course FOREIGN KEY(course_id) REFERENCES tb_course(id);

-- Liên kết bảng tb_user_course với tb_user và tb_course
ALTER TABLE tb_user_course ADD CONSTRAINT FK_user_course_user FOREIGN KEY(user_id) REFERENCES tb_user(id);
ALTER TABLE tb_user_course ADD CONSTRAINT FK_user_course_course FOREIGN KEY(course_id) REFERENCES tb_course(id);

-- Liên kết bảng tb_comment với tb_user (ở sơ đồ là person_id) và tb_course
ALTER TABLE tb_comment ADD CONSTRAINT FK_comment_user FOREIGN KEY(person_id) REFERENCES tb_user(id);
ALTER TABLE tb_comment ADD CONSTRAINT FK_comment_course FOREIGN KEY(course_id) REFERENCES tb_course(id);

