spring.application.name=course

server.port = 8080

# =================================
#      Oracle DB Connection
# =================================
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=sys AS SYSDBA
#spring.datasource.password=123123

#spring.datasource.url=jdbc:oracle:thin:@61.14.233.162:1521:xe
#spring.datasource.username=course
#spring.datasource.password=123456
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =================================
#      MYSQL DB Connection
# =================================
spring.datasource.url=jdbc:mysql://localhost:3307/sell_course_asm2
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =================================
#           JPA/Hibernate
# =================================
# update: l?n ??u tiên ch?y n?u không có b?ng thì nó s? t?o ra b?ng
# create: m?i l?n ch?y s? t?o ra b?ng
# create-drop: m?i l?n ch?y s? t?o l?i b?ng nh?ng khi stop s? xóa b?ng luôn
# none: s? không có thao tác gì vào DB
# update: l?n ??u tiên s? t?o table trong database, t? l?n sau tr? ?i n?u có thay ??i thì nó s? update vào database, còn không thì b? qua.
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect            // ? ORACLE DB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# ddl-auto: none - Không thay ??i schema c? s? d? li?u.
# show-sql: true - Hi?n th? câu l?nh SQL trong logs.
# format_sql: true - ??nh d?ng các câu l?nh SQL ?? d? ??c.
# dialect: org.hibernate.dialect.OracleDialect - S? d?ng Oracle dialect cho Hibernate.
# physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy - Chuy?n ??i tên camelCase sang snake_case trong c? s? d? li?u.

# =================================
#             Swagger
# =================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operationsSorter=alpha